#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
#
#  This file is part of os-installer
#
#  Copyright 2013-2016 Ikey Doherty <ikey@solus-project.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
from os_installer2.application import InstallerApplication
import sys

if __name__ == "__main__":
    app = InstallerApplication()
    app.run(sys.argv)
