#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
#  
#  Copyright (C) 2013-2016 Ikey Doherty <ikey@solus-project.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#

import gi.repository
from gi.repository import Gtk, GObject, Gdk
import gettext

from os_installer.interface import InstallerWindow

gettext.install("os-installer", "/usr/share/locale")

def main():
    GObject.threads_init()
    Gdk.threads_init()
    window = InstallerWindow()
    Gtk.main()


if __name__ == '__main__':
	main()

