#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
#
#  This file is part of os-installer
#
#  Copyright 2013-2016 Ikey Doherty <ikey@solus-project.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#

import sys
import os
from os_installer2.application import InstallerApplication
from os_installer2.permissions import PermissionsManager
from os_installer2 import SOURCE_FILESYSTEM
from gi.repository import Gdk, GObject, Gtk


if __name__ == "__main__":
    if os.geteuid() != 0:
        sys.stderr.write("You must be root to use OsInstaller\n")
        sys.stderr.flush()
        sys.exit(1)

    # No source filesystem? No cookies for you!
    if not os.path.exists(SOURCE_FILESYSTEM):
        msg = "Source file system is missing, cannot continue.\n\n{}".format(
            SOURCE_FILESYSTEM)

        d = Gtk.MessageDialog(parent=None, flags=Gtk.DialogFlags.MODAL,
                              type=Gtk.MessageType.WARNING,
                              buttons=Gtk.ButtonsType.OK_CANCEL,
                              message_format=msg)

        d.run()
        d.destroy()
        sys.exit(1)

    # Immediately drop permissions before we init GTK
    p = PermissionsManager()
    p.down_permissions()

    GObject.threads_init()
    Gdk.threads_init()

    app = InstallerApplication()
    r = app.run(sys.argv)
    sys.exit(r)
